parameters:
  - name: 'platform'
    type: string

steps:
  - script: |
      conda config --set always_yes yes --set changeps1 no
      conda update -q conda
      conda env create --file environment-host.yml
    displayName: Install dependencies

  - script: |
      source activate xeus-cling
      echo "#include <cctype>" > test.cpp
      clang++ -v -E test.cpp
      ./test
    displayName: Testing compilation with clangdev

  - script: |
      conda env create --file environment-build.yml
    displayName: Install conda-forge compilers

  - script: |
      source activate xeus-cling
      export PREFIX=$CONDA_PREFIX
      source deactivate
      source activate build-xeus-cling
      mkdir build
      cd build
      cmake -DCMAKE_PREFIX_PATH=$PREFIX -DCMAKE_INSTALL_PREFIX=$PREFIX -DDOWNLOAD_GTEST=ON -DCMAKE_INSTALL_LIBDIR=lib $(Build.SourcesDirectory)
    displayName: Configure xeus-cling
    workingDirectory: $(Build.BinariesDirectory)

  - script: |
      source activate build-xeus-cling 
      make install -j2
    displayName: Build xeus-cling
    workingDirectory: $(Build.BinariesDirectory)/build

  - script: |
      source activate xeus-cling
      ./test_xeus_cling
    displayName: Test xeus-cling (C++)
    workingDirectory: $(Build.BinariesDirectory)/build/test

  - script: |
      source activate xeus-cling
      py.test . -v;
    condition: eq('${{ parameters.platform }}', 'Linux')
    displayName: Test xeus-cling (Python)
    workingDirectory: $(Build.sourcesDirectory)/test

  - script: |
      source activate xeus-cling
      #mv /Applications/Xcode_14.0.1.app /Applications/_Cxode_14.0.1.app
      mv /Applications/Xcode.app /Applications/__Xcode.app
      mv /Library/Developer/CommandLineTools/ /Library/Developer/__CommandLineTools
      echo "Checking existence of /Applications/Xcode_14.0.1.app"
      ls /Applications/Xcode_14.0.1.app
      echo "Staring tests"
      #OSX_SDK_DIR="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
      #MACOSX_SDK_VERSION=10.9
      #export CONDA_BUILD_SYSROOT="${OSX_SDK_DIR}/MacOSX${MACOSX_SDK_VERSION}.sdk"
      #echo "Downloading ${MACOSX_SDK_VERSION} sdk"
      #curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/11.3/MacOSX${MACOSX_SDK_VERSION}.sdk.tar.xz
      #mkdir -p "$(dirname "$CONDA_BUILD_SYSROOT")"
      #tar -xf MacOSX${MACOSX_SDK_VERSION}.sdk.tar.xz -C "$(dirname "$CONDA_BUILD_SYSROOT")"
      #export SDKROOT=$CONDA_BUILD_SYSROOT
      #export MACOSX_DEPLOYMENT_TARGET=10.9
      #echo "SDKROOT = $SDKROOT"
      #echo "MACOSX_DEPLOYMANT_TARGET=$MACOSX_DEPLOYMENT_TARGET"
      py.test . -v;
    condition: eq('${{ parameters.platform }}', 'OSX')
    displayName: Test xeus-cling (Python)
    workingDirectory: $(Build.sourcesDirectory)/test
